# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "static/media" # Folder where user uploaded files should go
public_folder: "media"

# allow local visit
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [en, zh]
  default_locale: en


#    - name: "products"
#      label: "Products"
#      folder: "content/products"
#      path: "{{slug}}/index"
#      create: true
#      fields:
#        - { label: "Title", name: "title", widget: "string" }
#        - label: "Category"
#          name: "category"
#          widget: "select"
#          options: [ "category1", "category2", "category3" ]
#        - label: "Industry"
#          name: "industry"
#          widget: "select"
#          options: [ "industry3", "industry1", "industry2" ]
#        - { label: "Cover Image", name: "image", widget: "image" }
#        - { label: "Summary", name: "summary", widget: "text" }
#        - { label: "Body", name: "body", widget: "markdown" }
#        - { label: "Cover", name: "image", widget: "image" }


# collections configuration
collections:
  - name: "news"
    label: "news"
    folder: "content"
    path: "news/{{slug}}"
    filter: { field: "language", value: "en" }
    i18n:
      structure: multiple_folders
      locales: [english, chinese]
    create: true
    fields:
      [
        { label: "Type", name: "nType", widget: "string", i18n: "duplicate", default: "new" },
        { label: "Title", name: "title", widget: "string", i18n: true},
        { label: "Publish Date", name: "date", widget: "datetime", i18n: "duplicate" },
        { label: "Cover Image", name: "image", widget: "image" , i18n: true },
        { label: "Summary", name: "summary", widget: "text", i18n: true },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "sections"
    label: "Sections"
    i18n: 
      structure: single_file
      locales: [en, zh]
    files:
      - file: "data/home.yml"
        i18n: true
        label: "Home Section"
        name: "home"
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true},
            { label: "Slogan", name: "slogan", widget: string, i18n: true},
            { label: "Description", name: "shortDescription", widget: "text", i18n: true},
            { label: "Header Image", name: "image", widget: "image", i18n: true},
            { label: "register", name: "register", widget: string, i18n: true },
            { label: "copyright", name: "copyright", widget: string, i18n: true },
            { label: "Register Url", name: "registerUrl", widget: string, i18n: true },
          ]
      - file: "data/about.yml"
        label: "About Section"
        name: "about"
        i18n: true
        description: "Go to edit the about section"
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true},
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true},
            { label: "Items", name: "items", widget: "list", i18n: true, fields: [
              { label: "Icon", name: "icon", widget: string , i18n: true},
              { label: "Title", name: "title", widget: string, i18n: true},
              { label: "Content", name: "content", widget: text, i18n: true},
            ]}
          ]
      - file: "data/products.yml"
        label: "Production Section"
        name: "productions"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true},
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true},
            { label: "PortText", name: "portText", widget: "text", i18n: true},
            { label: "Categories", name: "categories", widget: "list", i18n: true, fields: [
              { label: "CoverImage", name: "coverImage", widget: string , i18n: true},
              { label: "Title", name: "title", widget: string, i18n: true},
              { label: "Description", name: "description", widget: text , i18n: true},
            ]}
          ]
      - file: "data/scenes.yml"
        label: "Industry Section"
        name: "industry"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true},
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true},
            { label: "PortText", name: "portText", widget: "text", i18n: true},
            { label: "scenes", name: "scenes", widget: "list", i18n: true, fields: [
              { label: "CoverImage", name: "coverImage", widget: string , i18n: true },
              { label: "Title", name: "title", widget: string, i18n: true },
              { label: "Description", name: "description", widget: text , i18n: true },
              { label: "icon", name: "icon", widget: string , i18n: true },
            ] }
          ]
      - file: "data/news.yml"
        label: "News Section"
        name: "news"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true},
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true},
            { label: "portText", name: "portText", widget: string, i18n: true },
          ]
      - file: "data/contact.yml"
        label: "Contact Section"
        name: "contact"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true},
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true},
            { label: "Subtitle", name: "subtitle", widget: string, i18n: true},
            { label: "Detail", name: "detail", widget: string, i18n: true},
            { label: "Location", name: "location", widget: string , i18n: true},
            { label: "Email", name: "email", widget: string , i18n: true},
            { label: "Fax", name: "fax", widget: string, i18n: true},
            { label: "Phone", name: "phone", widget: string , i18n: true},
            { label: "Languages", name: "languages", widget: string, i18n: true},
          ]
