# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "static/media" # Folder where user uploaded files should go
public_folder: "media"

# allow local visit
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [ en, zh ]
  default_locale: en


# collections configuration
collections:
  - name: "news"
    label: "News-EN"
    folder: "content/english/news"
    path: "{{slug}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Publish Date", name: "date", widget: "datetime"},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "news-zh"
    label: "News-中文"
    folder: "content/chinese/news"
    path: "{{slug}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Publish Date", name: "date", widget: "datetime", i18n: "duplicate" },
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "products"
    label: "Products-EN"
    folder: "content/english/products"
    path: "{{slug}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string"},
        { label: "Category", name: "categories", widget: "select", multiple: true, options:  [
          { label: "纤维素醚", value: "c1" },
          { label: "钛白粉", value: "c2" },
          { label: "氧化铁颜料", value: "c3" },
          { label: "可再分散乳胶粉", value: "c4" },
          { label: "其他建筑、涂料助剂", value: "c5" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "products-zh"
    label: "Products-中文"
    folder: "content/chinese/products"
    path: "{{slug}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string"},
        { label: "Category", name: "categories", widget: "select", multiple: true, options:  [
          { label: "纤维素醚", value: "c1" },
          { label: "钛白粉", value: "c2" },
          { label: "氧化铁颜料", value: "c3" },
          { label: "可再分散乳胶粉", value: "c4" },
          { label: "其他建筑、涂料助剂", value: "c5" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "scene"
    label: "Scene-EN"
    folder: "content/english/scenes"
    path: "{{slug}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Scene", name: "scenes", widget: "select", multiple: true, options:  [
          { label: "化工", value: "s1" },
          { label: "食品", value: "s2" },
          { label: "石油", value: "s3" },
          { label: "制药", value: "s4" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "scene-zh"
    label: "Scene-中文"
    folder: "content/chinese/scenes"
    path: "{{slug}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Scene", name: "scenes", widget: "select", multiple: true, options:  [
          { label: "化工", value: "s1" },
          { label: "食品", value: "s2" },
          { label: "石油", value: "s3" },
          { label: "制药", value: "s4" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "sections"
    label: "Sections"
    i18n:
      structure: single_file
      locales: [ en, zh ]
    files:
      - file: "data/home.yml"
        i18n: true
        label: "首页-Home"
        name: "home"
        fields: [
          { label: "Title", name: "title", widget: string, i18n: true },
          { label: "Slogan", name: "slogan", widget: string, i18n: true },
          { label: "Description", name: "shortDescription", widget: "text", i18n: true },
          { label: "Header Image", name: "image", widget: "image" , media_folder: "/static/media", i18n: true },
          { label: "注册", name: "register", widget: string, i18n: true },
          { label: "版权", name: "copyright", widget: string, i18n: true },
        ]
      - file: "data/about.yml"
        label: "首页-关于我们"
        name: "about"
        i18n: true
        description: "Go to edit the about section"
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "Items", name: "items", widget: "list", i18n: true, fields: [
              { label: "Icon", name: "icon", widget: string , i18n: true },
              { label: "Title", name: "title", widget: string, i18n: true },
              { label: "Content", name: "content", widget: text, i18n: true }]
            }
          ]
      - file: "data/products.yml"
        label: "首页-产品"
        name: "productions"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "PortText", name: "portText", widget: "text", i18n: true },
            { label: "Categories", name: "categories", widget: "list", i18n: true, fields: [
              { label: "CoverImage", name: "coverImage", widget: "image" , media_folder: "/static/media", i18n: true },
              { label: "Name", name: "name", widget: string, i18n: true },
              { label: "Category", name: "cSlug", widget: select, i18n: true, options: [
                { label: "纤维素醚", value: "c1" },
                { label: "钛白粉", value: "c2" },
                { label: "氧化铁颜料", value: "c3" },
                { label: "可再分散乳胶粉", value: "c4" },
                { label: "其他建筑、涂料助剂", value: "c5" },
              ] },
              { label: "Description", name: "description", widget: text , i18n: true },
            ] }
          ]
      - file: "data/scenes.yml"
        label: "首页-场景"
        name: "industry"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "PortText", name: "portText", widget: "text", i18n: true },
            { label: "scenes", name: "scenes", widget: "list", i18n: true, fields: [
              { label: "CoverImage", name: "coverImage", widget: "image" , media_folder: "/static/media", i18n: true },
              { label: "Name", name: "name", widget: string, i18n: true },
              { label: "Scene", name: "cSlug", widget: select, i18n: true, options: [
                { label: "化工", value: "s1" },
                { label: "食品", value: "s2" },
                { label: "石油", value: "s3" },
                { label: "制药", value: "s4" },
              ] },
              { label: "Description", name: "description", widget: text , i18n: true },
              { label: "icon", name: "icon", widget: string , i18n: true },
            ] }
          ]
      - file: "data/news.yml"
        label: "首页-新闻"
        name: "news"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "portText", name: "portText", widget: string, i18n: true },
          ]
      - file: "data/contact.yml"
        label: "首页-联系我们"
        name: "contact"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "Subtitle", name: "subtitle", widget: string, i18n: true },
            { label: "Detail", name: "detail", widget: string, i18n: true },
            { label: "Location", name: "location", widget: string , i18n: true },
            { label: "Email", name: "email", widget: string , i18n: true },
            { label: "Fax", name: "fax", widget: string, i18n: true },
            { label: "Phone", name: "phone", widget: string , i18n: true },
            { label: "Languages", name: "languages", widget: string, i18n: true },
          ]
      - file: "data/glossary.yml"
        label: "词汇表"
        name: "glossary"
        i18n: true
        fields:
          [
            { label: "home", name: "home", widget: string, i18n: true },
            { label: "about", name: "about", widget: string, i18n: true },
            { label: "product", name: "product", widget: string, i18n: true },
            { label: "solution", name: "solution", widget: string, i18n: true },
            { label: "news", name: "news", widget: string, i18n: true },
            { label: "contact", name: "contact", widget: string, i18n: true },
            { label: "list", name: "list", widget: string, i18n: true },
          ]