# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "static/media" # Folder where user uploaded files should go
public_folder: "media"

# allow local visit
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support


# collections configuration
collections:
  - name: "news"
    identifier_field: name
    label: "News"
    folder: "content/news"
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "sections"
    label: "Sections"
    files:
      - file: "data/home.yml"
        label: "Home Section"
        name: "home"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "Slogan", name: "slogan", widget: string },
            { label: "Description", name: "shortDescription", widget: "text" },
            { label: "Header Image", name: "image", widget: "image" }
          ]
      - file: "data/about.yml"
        label: "About Section"
        name: "about"
        description: "Go to edit the about section"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string },
            { label: "Items", name: "items", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: string },
              { label: "Title", name: "title", widget: string },
              { label: "Content", name: "content", widget: text },
            ]}
          ]