# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "static/media" # Folder where user uploaded files should go
public_folder: "media"

# allow local visit
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support


# collections configuration
collections:
  - name: "products"
    identifier_field: name
    label: "Products"
    folder: "content/products"
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["category1", "category2", "category3"]
      - label: "Industry"
        name: "industry"
        widget: "select"
        options: ["industry3", "industry1", "industry2"]
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Cover", name: "image", widget: "image" }
  - name: "news"
    identifier_field: name
    label: "News"
    folder: "content/news"
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "sections"
    label: "Sections"
    files:
      - file: "data/home.yml"
        label: "Home Section"
        name: "home"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "Slogan", name: "slogan", widget: string },
            { label: "Description", name: "shortDescription", widget: "text" },
            { label: "Header Image", name: "image", widget: "image" }
          ]
      - file: "data/about.yml"
        label: "About Section"
        name: "about"
        description: "Go to edit the about section"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string },
            { label: "Items", name: "items", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: string },
              { label: "Title", name: "title", widget: string },
              { label: "Content", name: "content", widget: text },
            ]}
          ]
      - file: "data/products.yml"
        label: "Production Section"
        name: "productions"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string },
            { label: "PortText", name: "portText", widget: "text" },
            { label: "Items", name: "items", widget: "list", fields: [
              { label: "CoverImage", name: "coverImage", widget: string },
              { label: "Title", name: "title", widget: string },
              { label: "Description", name: "description", widget: text },
            ]}
          ]
      - file: "data/scenes.yml"
        label: "Industry Section"
        name: "industry"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string },
            { label: "PortText", name: "portText", widget: "text" },
          ]
      - file: "data/news.yml"
        label: "News Section"
        name: "news"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string },
          ]
      - file: "data/contact.yml"
        label: "Contact Section"
        name: "contact"
        fields:
          [
            { label: "Title", name: "title", widget: string },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string },
            { label: "Subtitle", name: "subtitle", widget: string },
            { label: "Detail", name: "detail", widget: string },
            { label: "Location", name: "location", widget: string },
            { label: "Email", name: "email", widget: string },
            { label: "Fax", name: "fax", widget: string },
            { label: "Phone", name: "phone", widget: string },
            { label: "Languages", name: "languages", widget: string },

          ]
